spring:
  application:
    name: stock-service
    
server:
 port: 8303
 
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
  instance:
    hostname: localhost