spring:
  application:
    name: stock-service
  config:
    enabled: true
    import: "optional:configserver:http://localhost:8305"


server:
 port: 8303
 
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8301/eureka
#    helthcheck:
#      enabled: true
#      lease:
#        duration: 5
#  instance:
#    hostname: localhost
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 2





resilience4j:
  circuitbreaker:
    instances:
      StockService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

resilience4j.retry:
  instances:
    StockService:
      registerHealthIndicator: true
      maxAttempts: 3
      waitDuration: 10s


management:
  security:
    enabled: false
  health:
    circuitbreakers:
      enable: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
